### ISSUE TITLE
VBA-PPT-ColorPicker issue

### ISSUE THREAD

**Issue by abhi27us** [ericaddison/VBA-PPT-ColorPicker#1]
Can you share the .pptm file for use as when I import the .frm file it gives an error. Please advise.

**Comment by ericaddison** [comment]
Sure :)

I'll push that to a separate branch in the next night or two.

**Comment by abhi27us** [comment]
Thanks a ton!!!

**Comment by ericaddison** [comment]
@abhi27us 
OK, I added a demo folder with a simple `pptm` presentation that has the form already loaded.

Let me know how it goes!

**Comment by abhi27us** [comment]
thank you it works great

**Comment by abhi27us** [comment]
Thanks Eric.Merry Christmas and happy New Year.

Best

Abhinav
------------------------------------
kindly ignore typos

________________________________

**Comment by ericaddison** [comment]
You too :)
