### ISSUE TITLE
Can we add a box to display HEX colour values in the userform?

### ISSUE THREAD

**Issue by shoeblakhi** [ericaddison/VBA-PPT-ColorPicker#2]
Just wondering if there is a way to add another box on the userform which also displays the HEX values of the selected colour?

**Comment by ericaddison** [comment]
Thanks for humoring me, @shoeblakhi... Do you just want to display the hex value when you select a color, or would you like to be able to input a hex value as well?

**Comment by shoeblakhi** [comment]
Hi Eric, actually both the scenarios, as currently, the Long and RGB box values change depending on when any of the value is added, so ideally, if even the HEX box can achieve the same effect, it will be fantastic.

**Comment by ericaddison** [comment]
Sure thing :)
I can tweak that in the next evening or two ... this isn't a time sensitive thing, is it?

**Comment by shoeblakhi** [comment]
Thanks Eric, please take your time on this, no rush at all :-)

**Comment by ericaddison** [comment]
@shoeblakhi 
OK, I put a hex field in the dialog. Works as input and also just display. Let me know if it works!

**Comment by shoeblakhi** [comment]
This is perfect....thanks a lot Eric, really appreciate you taking time out for this.
